### ISSUE TITLE
Non written char pointers should be const

### ISSUE THREAD

**Issue by astrelsky** [shahpiyushv/json_parser#1]
https://github.com/shahpiyushv/json_parser/blob/d049e7103f667c53a45bee5d27b7c15cb13b48c7/src/json_parser.c#L369

This should be:
```c
int json_parse_start(jparse_ctx_t *jctx, const char *js, int len)
```

Because of this you cannot do the following:
```c++
std::string data = getJsonString();
jparse_ctx_t jctx;
json_parse_start(&jctx, data.c_str(), data.length());
// ...
```

**Comment by MartinK7** [comment]
> https://github.com/shahpiyushv/json_parser/blob/d049e7103f667c53a45bee5d27b7c15cb13b48c7/src/json_parser.c#L369
> 
> This should be:
> 
> ```c
> int json_parse_start(jparse_ctx_t *jctx, const char *js, int len)
> ```
> 
> Because of this you cannot do the following:
> 
> ```c++
> std::string data = getJsonString();
> jparse_ctx_t jctx;
> json_parse_start(&jctx, data.c_str(), data.length());
> // ...
> ```

This issue has been solved [link-commit](https://github.com/shahpiyushv/json_parser/commit/82d67452d3743f331a1c2b96b1b0d18e5a5a7cf4)

**Comment by shahpiyushv** [comment]
Indeed. Thanks @MartinK7 for your contribution.  Closing this issue now.
